### ISSUE TITLE
ssh: handshake failed

### ISSUE THREAD

**Issue by Ygilany** [appleboy/drone-ssh#110]
I keep getting the following error.. I have many repos already setup and the drone-ssh plugin work fine with them. this only happens on some of them.
```
ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
0s
exit code 1
```
my drone.yml:
```
pipeline:
  build:
    image: node:8.1
    commands:
      - npm install -q
      - npm run lint
      - npm run babel
      - npm run webpack
  ssh:
    pull: true
    image: appleboy/drone-ssh
    host: myserver.com
    username: myuser
    secrets: [ ssh_key ]
    port: 22
    script:
      - cd /path/to/app && git pull && npm install && npm run webpack && pm2 reload process.json -s
    when:
      status: success
      event: [push]
      branch: master
```
I'm using drone 0.8
drone-cli 0.8
my project settings: (from `drone repo info org/repo`)
```
Owner: org
Repo: repo
Type: git
Config: .drone.yml
Visibility: private
Private: true
Trusted: true
Gated: false
Remote: https://git.company.com/org/repo.git
```

**Comment by varp** [comment]
+1

**Comment by sebster2** [comment]
@appleboy I'm also having this issue, any ideas?

**Comment by appleboy** [comment]
@Ygilany do you run the build from drone-cli or drone server?

**Comment by Ygilany** [comment]
The server. They kickoff automatically with every push to git

**Comment by varp** [comment]
Ok! I switched to username and password and the issue is gone... So, the issue only appears when I using key file

**Comment by appleboy** [comment]
@Ygilany @varp How do you add the `ssh_key`? drone-cli or web console? show your command if drone-cli.

**Comment by varp** [comment]
I set parameter `key_path`

**Comment by Ygilany** [comment]
@appleboy I used the web console

**Comment by appleboy** [comment]
@varp See https://github.com/appleboy/drone-ssh/issues/51#issuecomment-332855580

**Comment by varp** [comment]
I understood @appleboy . Thx

**Comment by sebster2** [comment]
@appleboy do you have any update on @Ygilany issue?

**Comment by appleboy** [comment]
@sebster2 NO, maybe you can try the ssh command on drone machine using the ssh key file.

**Comment by itsnauman** [comment]
I am also having this issue. Does anyone have a solution?

**Comment by mebibou** [comment]
I've spend quite a lot of time to fix the issue myself, would it be possible to have a verbose mode to see what's going on?
otherwise the config that worked for me:
```
pipeline:
  publish:
    image: appleboy/drone-ssh
    host: host.com
    username: user
    port: 22
    key_path: /root/.ssh/id_rsa
    volumes:
      - /root/.ssh/id_rsa:/root/.ssh/id_rsa
```

**Comment by yeyongyong** [comment]
![image](https://user-images.githubusercontent.com/14305099/43558966-7855c51c-963e-11e8-81df-5a5731d942c4.png)
![image](https://user-images.githubusercontent.com/14305099/43558988-8e97e12a-963e-11e8-916c-750b91cf166d.png)

**Comment by yeyongyong** [comment]
![image](https://user-images.githubusercontent.com/14305099/43559161-8139d2c6-963f-11e8-84f9-366ebc14672c.png)
![image](https://user-images.githubusercontent.com/14305099/43559167-85b7891a-963f-11e8-8b1f-5565079a6933.png)

**Comment by lddsb** [comment]
**same issue for me.**
> this is my `.drone.yml`:
```yaml
pipeline:
    ssh:
        image: appleboy/drone-ssh:latest
        host: 
            - www.dev.codepku.com
        username: ubuntu
        # secrets: [ ssh_key ]
        environment:
            - DEBUG=true
        volumes:
            - /root/.ssh/drone_rsa:/root/.ssh/drone_rsa
        key_path: /root/.ssh/drone_rsa
        script:
            - ls
            - pwd
            - cd /home/ubuntu && touch
        when:
            branch: master
```
> this is my drone in compose file:
```yaml
services:
     drone-server:
         image: drone/drone:alpine
         container_name: drones
         restart: always
         networks:
             - webnet
         volumes:
             - '/srv/drone:/var/lib/drone'
         environment:
             - DRONE_DEBUG=true
             - DRONE_OPEN=true
             - DRONE_SECRET="my_secrets"
     drone-agent:
         image: drone/agent:alpine
         container_name: dronea
         networks:
             - webnet
         depends_on:
             - drone-server
         restart: always
         volumes:
             - /var/run/docker.sock:/var/run/docker.sock
             - ./drone/drone_rsa:/root/.ssh/drone_rsa
         environment:
             - DRONE_DEBUG=true
             - DRONE_SERVER=drone-server:9000
             - DRONE_SECRET="my_secrets"
```

**Comment by lddsb** [comment]
![image](https://user-images.githubusercontent.com/20765867/48544860-7f02e200-e8ff-11e8-8b6d-a54a2af327b8.png)

**Comment by appleboy** [comment]
@lddsb Try the secret. https://0-8-0.docs.drone.io/manage-secrets/

**Comment by lddsb** [comment]
@appleboy thanks so much,it's work for me.
```yaml
pipeline:
  dev-update:
    image: appleboy/drone-ssh
    username: ubuntu
    secrets:
        - source: DRONE_RSA
          target: ssh_key
        - source: HOST_NAME
          target: ssh_host
```
> It need setting secret variables on drone web menu like `drone_rsa` and `host_name`
