### ISSUE TITLE
Forwarded environment variables are not exported

### ISSUE THREAD

**Issue by joshdk** [appleboy/drone-ssh#115]
Passing environment variables to programs on the target host is overly complex. If I want a script that resides on the SSH host to consume a specific environment variable, I have to reference it in **three** different places.

In this example, the `aws` cli will error because there is no secret access key in its working environment:

```yaml
pipeline:
  ssh:
    image: appleboy/drone-ssh
    ...
    secrets:
    - aws_secret_access_key
    envs:
    - AWS_SECRET_ACCESS_KEY
    script:
    - aws sts get-caller-identity
```

This is solved in the following example my explicitly exporting the `AWS_SECRET_ACCESS_KEY` variable, so that it now becomes available to the `aws` cli.

```diff
 pipeline:
   ssh:
     image: appleboy/drone-ssh
     ...
     secrets:
     - aws_secret_access_key
     envs:
     - AWS_SECRET_ACCESS_KEY
     script:
+    - export AWS_SECRET_ACCESS_KEY
     - aws sts get-caller-identity
```

This is not necessarily a bug, as the variables are implicitly available to the shell on the SSH host, and optionally/explicitly available to exec'd programs.

I'm just trying to think if there is a strong argument for **not** exporting the variables. "Of course I want this variable exported, why **wouldn't** I?"

Cheers!
