### ISSUE TITLE
SSH: Handshake failure

### ISSUE THREAD

**Issue by itsnauman** [appleboy/drone-ssh#120]
Hi, I'm following the tutorial published by `appleboy` but I'm still getting a handshake failure 

Pipeline code:

```
pipeline:
  ssh:
    image: appleboy/drone-ssh
    host: xxxx
    username: ubuntu
    port: 22
    volumes:
      - /root/id_rsa:/root/ssh/id_rsa
    key_path: /root/ssh/id_rsa
    script:
      - echo Hello World

```

Docker compose
```
version: '3'

services:
  drone-server:
    image: drone/drone:0.7
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - /var/lib/drone:/var/lib/drone
    restart: always
    env_file:
      - /etc/drone/server.env

  drone-agent:
    image: drone/drone:0.7
    command: agent
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.ssh/id_rsa:/root/id_rsa
    restart: always
    env_file:
      - /etc/drone/agent.env
```
