### ISSUE TITLE
Logs in as TTY. Can't find pm2 process to run

### ISSUE THREAD

**Issue by rakshith-ravi** [appleboy/drone-ssh#129]
I have a simple script that logs in to the server and executes pm2 reload. But it never seems to be able to find the pm2 executable. Is this a problem with my pm2 configuration or with drone-ssh?

**Comment by appleboy** [comment]
@rakshith-ravi Maybe you can export `PATH` first and add bin folder path of node?

**Comment by rakshith-ravi** [comment]
The problem is that nvm handles the PATH of the node_modules/bin directory based on what version of node is selected. So I wouldn't know the directory to pm2 before hand. Is there any way I can make it work just like I'm logging in from my terminal?

**Comment by appleboy** [comment]
Try the following command?

```
$ nvm use stable (or some version you need.)
$ pm2 restart app
```

**Comment by rakshith-ravi** [comment]
I still get this:

```
err: bash: line 13: HOME: command not found  
err: bash: line 14: nvm: command not found  
err: bash: line 15: pm2: command not found
```

**Comment by appleboy** [comment]
create Makefile:

```makefile
export NVM_DIR=$(HOME)/.nvm
export NODE_VERSION=6.10.0

deploy:
	. $(NVM_DIR)/nvm.sh && nvm use $(NODE_VERSION) > /dev/null 2>&1; \
	if [ $$? -ne 0 ]; then \
		nvm install $(NODE_VERSION); \
	fi && \
	hash pm2 > /dev/null 2>&1; if [ $$? -ne 0 ]; then \
		npm install -g pm2; \
	fi && \
	hash babel > /dev/null 2>&1; if [ $$? -ne 0 ]; then \
		npm install -g babel; \
	fi && \
	hash yarn > /dev/null 2>&1; if [ $$? -ne 0 ]; then \
		npm install -g yarn; \
	fi
```

in drone.yml

```yml
  ssh_production:
    image: appleboy/drone-ssh
    pull: true
    host:
      - 10.130.32.6
      - 10.130.35.6
    port: 22
    user: deploy
    script:
      - rm -rf mcs-api && mkdir mcs-api
      - tar -zxmf /home/deploy/drone/${DRONE_REPO}/release.tar.gz -C mcs-api
      - cd mcs-api && make deploy target=production
    when:
      event: tag
      branch: global-*
```
