### ISSUE TITLE
Secret in Drone 1.0.0-rc.1

### ISSUE THREAD

**Issue by SolT31** [appleboy/drone-ssh#130]
How to use secrets in script?
Drone version 1.0.0-rc.1

```
ssh:
    image: appleboy/drone-ssh
    host: host.com
    username: 
      from_secret: ssh_user
    password:
      from_secret: ssh_password
    port: 22
    script:
      - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} repo.com
```

Example from documentation does not work for version 1.0.0 rc.1

**Comment by appleboy** [comment]
```yml
- name: ssh
  image: appleboy/drone-ssh
  settings:
    host: host.com
    username:
      from_secret: ssh_user
    password:
      from_secret: ssh_password
    port: 22
    script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} repo.com
```

see the `plugins` section of [pipeline steps](https://docs.drone.io/config/pipeline/steps/)

```yml
kind: pipeline
name: default

steps:
- name: build
  image: golang
  commands:
  - go build
  - go test

- name: notify
  image: plugins/slack
  settings:
    room: general
    webhook: https://...
```

**Comment by coolyrat** [comment]
it would be great if add some example usage for 1.0.0. i am trying to pass secret into the executing script

![image](https://user-images.githubusercontent.com/1881159/48895901-2e503380-ee81-11e8-95f4-848fd5dada03.png)

**Comment by v7lin** [comment]
I have the same problem.

````
- name: ssh-docker-host
  image: appleboy/drone-ssh
  settings:
    host: host.docker.internal
    port: 22
    username:
      from_secret: MAC_USER
    password:
      from_secret: MAC_PASSWORD
    script:
    - date -R
    - system_profiler SPSoftwareDataType
    - bash -lc 'security unlock-keychain -p ${MAC_PASSWORD} login.keychain'
    - bash -lc 'flutter --version'
    - date -R
````
Example from documentation does not work for version 1.0.0 rc.1

**Comment by v7lin** [comment]
^_^ I have solved it.

````
- name: ssh-docker-host
  image: appleboy/drone-ssh
  environment:
    USERNAME:
      from_secret: MAC_USER
  settings:
    host: host.docker.internal
    port: 22
    username:
      from_secret: MAC_USER
    password:
      from_secret: MAC_PASSWORD
    envs: [ USERNAME ]
    script:
    - date -R
    - system_profiler SPSoftwareDataType
    - bash -lc 'flutter --version'
    - echo $USERNAME
    - echo $${USERNAME}
    - date -R
````

**Comment by coltenkrauter** [comment]
@v7lin 
Can you please help me? I cannot get secrets to work in scripts...
I created a secret names ```test``` and I am trying to use it in ssh command.
This is what I have tried:
```
- name: Deploy gateway-service
  image: plugins/ssh
  environment:
    TEST:
      from_secret: test
  settings:
    host: coltenkrauter.com
    ssh_key: 
      from_secret: ssh_key
    port: 22
    envs: [TEST]
    script:
      - cd /home/ubuntu
      - echo test
      - echo TEST
      - echo $test
      - echo $${test}
      - echo "$test"
      - echo "$${test}"
      - echo $TEST
      - echo $${TEST}
      - echo "$TEST"
      - echo "$${TEST}"
      - pwd
      - whoami
```

**Comment by v7lin** [comment]
plugins/ssh -> appleboy/drone-ssh

**Comment by coltenkrauter** [comment]
That did it, thanks @v7lin

**Comment by leafney** [comment]
thanks @v7lin ,the `envs`  is the key.

**Comment by lkqm** [comment]
I have a similar problem, echo secret var like *******, causes docker login password error, 
and test other when secret value euqals drone secret it's will replaced ******:

using drone v1.6.0:

.drone.yml:
```yml
- name: deploy
  image: appleboy/drone-ssh
  environment:
    DOCKER_USER: mmd
    DOCKER_PASS:
      from_secret: docker_pass
  settings:
    host: mario6.me
    port: 6722
    username:
      from_secret: ssh_user_host1
    password:
      from_secret: ssh_pass_host1
    command_timeout: 2m
    envs: [ DOCKER_USER, DOCKER_PASS ]
    script:
      - export DOCKER_REGISTRY=registry.cn-chengdu.aliyuncs.com
      - export DOCKER_IMAGE=registry.cn-chengdu.aliyuncs.com/lkqm/paper-show:${DRONE_TAG=latest}
      - export DOCKER_REGISTRY_USER=$DOCKER_USER
      - export DOCKER_REGISTRY_PASS=$DOCKER_PASS
      - export PATH=/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
      - echo $DOCKER_USER
      - echo ${DOCKER_USER}
      - echo $${DOCKER_USER}
      - echo $DOCKER_PASS
      - echo ${DOCKER_PASS}
      - echo $${DOCKER_PASS}

      - sh /tmp/paper-show/drone/deploy.sh
  when:
    event:
      - tag
```

build result:
![image](https://user-images.githubusercontent.com/20638840/66703340-2cff5200-ed44-11e9-8218-c445758e0867.png)
