### ISSUE TITLE
Commands or script block in yaml?

### ISSUE THREAD

**Issue by apechkin** [appleboy/drone-ssh#131]
Greetings!

In my project i use drone 1.0.0 rc version.
If i use "commands" block in drone.yaml with next code:

```
kind: pipeline
name: constructor
steps:
  - name: ssh
    image: appleboy/drone-ssh
    when:
      branch:
        - mybranch
    host: my.host
    username:
      from_secret: ssh_user
    password:
      from_secret: ssh_password
    port: 22
    commands:
      - echo "Here we are"
      - ls -la
      - docker ps -a
```
i get an error:

```
+ echo "Here we are"
Here we are
+ ls -la
total 208
drwxr-xr-x    6 root     root          4096 Nov 23 09:44 .
drwxr-xr-x    3 root     root          4096 Nov 23 09:44 ..
-rw-r--r--    1 root     root            53 Nov 23 09:44 .drone.sh
-rw-r--r--    1 root     root           781 Nov 23 09:44 .drone.yml
...
...
...
-rw-r--r--    1 root     root           602 Nov 23 09:44 package.json
+ docker ps -a
/bin/droneinit: line 23: docker: not found
```

if i replace **commands** to **script**, get a next result:

```
1     ==========================================   0s
2     Successfully executed commands to all host.  0s
3     ==========================================   0s

```
But no one command are executed. How to execute docker commands in container ?
