### ISSUE TITLE
Migrating Configs from 0.8.0

### ISSUE THREAD

**Issue by TheGiddyLimit** [appleboy/drone-ssh#132]
How should SSH keys be specified in the new Drone config layout? I'm encountering the message:
`Error: can't connect without a private SSH key or password` 
Using the following config:
```yaml
steps:
- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: <snip>
    port: <snip>
    username: root
    key:
      from_secret: ssh_key
    script:
      - bash /scripts/script-deploy.sh
```

For reference, the old (previously working in 0.8.0) config:
```yaml
pipeline:
  Deploy:
    image: appleboy/drone-ssh
    host: <snip>
    port: <snip>
    user: root
    secrets: [ ssh_key ]
    script:
      - bash /scripts/script-deploy.sh
```

---

I've tried various combinations of parameters with no luck. In general, I think a fully-featured 1.0.0 guide would be useful to have.

(As an aside, removing the `username: root` (or `user: root`, which I've also tried) _doesn't_ cause an `Error: missing server host or user` error to be thrown. Unsure if this is relevant.)

**Comment by byumov** [comment]
Works for me:
```
kind: pipeline
name: some name

steps:
- name: run
  image: appleboy/drone-ssh
  settings:
    host: xxxxxxx
    port: 22
    username: xxxxxx
    key:
      from_secret: ssh_key
    script:
    - hostname
```

**Comment by TheGiddyLimit** [comment]
Seems there was probably just an update required. Adding `pull` fixed it, e.g.:
```yaml
steps:
- name: deploy
  image: appleboy/drone-ssh
  pull: true
  settings:
     ...
```
