### ISSUE TITLE
Correct syntax for envs

### ISSUE THREAD

**Issue by iatsiuk** [appleboy/drone-ssh#135]
Can you please suggest me correct syntax for secrets/envs combination for Drone 1.0?

This config:
```yml
kind: pipeline
name: default

steps:
  - name: deploy_master
    image: appleboy/drone-ssh
    when:
      event:
        - push
      branch:
        - master
    settings:
      host: xxx.xxx.xxx.xxx
      port: 22
      username:
        from_secret: ssh_username
      ssh_key:
        from_secret: ssh_private_key
      secrets: [ssh_deploy_key]
      envs: [ssh_deploy_key]
      script:
        - mkdir -p /opt/drone-cd/${DRONE_COMMIT}
        - cd /opt/drone-cd/${DRONE_COMMIT}
        - echo "${SSH_DEPLOY_KEY}" > ssh_deploy_key
```

Output (i.e. empty $SSH_DEPLOY_KEY var):

```
======CMD======
mkdir -p /opt/drone-cd/52ea317ec26534a7496255bddda566789887a229
cd /opt/drone-cd/52ea317ec26534a7496255bddda566789887a229
echo "" > ssh_deploy_key
chmod -R 400 ssh_deploy_key
======END======
```
