### ISSUE TITLE
Migrate to drone 1.0 version and move to cloud.drone.io

### ISSUE THREAD

**Issue by appleboy** [appleboy/drone-ssh#136]

**Comment by rakshith-ravi** [comment]
Any sort of documentation on how to use this plugin with drone 1.0 would be appreciated. I'm trying to get this running on 1.0 and it's being very difficult for me. Keeps saying the following:

```bash
sh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
```

I'm clearly doing something wrong with the syntax of how to use this plugin (cuz it's not trying anything to authenticate) but any help on how to use this with drone 1.0 would be appreciated.

**Comment by appleboy** [comment]
@rakshith-ravi Post your drone config.

**Comment by rakshith-ravi** [comment]
Currently, this is what I'm doing:
``` yaml
- name: "Deploy for staging"
    image: appleboy/drone-ssh
    settings:
      host:
        - example.com
      username:
        from_secret: ssh_username
      key:
        from_secret: ssh_key
      commands:
        - "[ -s ~/.nvm/nvm.sh ] && source ~/.nvm/nvm.sh"
        - nvm use default
        - mv app /var/www/app
        - ..... other commands
    when:
      event:
        - push
      branch:
        - staging
```
