### ISSUE TITLE
Access drone v1 secrets in appleboy/drone-ssh script section

### ISSUE THREAD

**Issue by DNajjarzade** [appleboy/drone-ssh#141]
Greetings Dear community,
These secrets [prod_ssh_username & prod_ssh_password] work and I can ssh into destination host so I think drone is working.
but all my tries to get the bbp secret using in script section fail.

```
REPOSITORY          TAG               IMAGE ID
drone/drone              1                    89752c9cb739
ppleboy/drone-ssh   latest             1858d153b41f


- name: prod
  image: appleboy/drone-ssh
  pull: always
  when:
    event:
      - push
    branch:
      - prod
  environment:
    bbp:
      from_secret: bbp
  settings:
    host: x.x.x.x
    port: 22
    username:
      from_secret: prod_ssh_username
    password: 
      from_secret: prod_ssh_password
    bbp:
      from_secret: bbp
    envs: [bbp]
    script:
      - cd /var/www/html/
      - echo $bbp
      - echo ${bbp}
      - echo $${bbp}
```
---

this is the drone output:
```

======CMD======
cd /var/www/html/
echo $bbp
echo 
echo ${bbp}
======END====== 
out:
out:
out:

```
I have rad all the toppics avilable.
in other solved issues the variable (bbp in my case) is only defined below environment, and not in settings section, i have testet without the settings section too with no luck.
what am I missing? Any help is appreciated.
Thank you for your time.
