### ISSUE TITLE
Error: missing server host 

### ISSUE THREAD

**Issue by UstyuzhaninAV** [appleboy/drone-ssh#144]
This doesn't seem to work anymore

>   ssh:
>     image: appleboy/drone-ssh
>     settings:
>       host: 10.10.10.10
>       username: god
>       port: 22
>       key: [ ssh_key ]
>       script:
>         - echo hello

**Comment by curder** [comment]
I got the same issue, when I deploy my code on https://cloud.drone.io.

this is my `.drone.yml` content:

```
pipeline:
  ssh:
    image: appleboy/drone-ssh
    settings:
      host: 
        from_secret: ssh_host
      username: 
        from_secret: ssh_username
      key:
        from_secret: ssh_key
      port:
        from_secret: ssh_port
      script:
        - echo "hello"
        - echo "world"
```

and under variables set in my project settings link this:

![image](https://user-images.githubusercontent.com/8327004/63245848-b9851b00-c293-11e9-917e-5de52b77b2a6.png)

when I push commit to git repository, I got the same error:

![image](https://user-images.githubusercontent.com/8327004/63245870-cace2780-c293-11e9-8a2d-125bec6cfa07.png)

**Comment by curder** [comment]
Hi:

I was resolved this by the below config:

- `.drone.yml`
```
kind: pipeline
name: default
steps:
- name: ssh
  image: appleboy/drone-ssh
  settings:
    host: 
      from_secret: ssh_host
    username: 
      from_secret: ssh_username
    key: 
      from_secret: ssh_key
    port: 
      from_secret: ssh_port
    script:
      - echo "hello"
      - echo "deploy"
```

- secret config

![image](https://user-images.githubusercontent.com/8327004/63254604-99ab2280-c2a6-11e9-8b3f-92eda23cf16b.png)

- deploy pipline
![image](https://user-images.githubusercontent.com/8327004/63254516-78e2cd00-c2a6-11e9-97e2-b4cd37c2ca91.png)

Thank you for your issue. 

happy coding...
