### ISSUE TITLE
plugin demo on drone website in old format (<v1.0)

### ISSUE THREAD

**Issue by arcolife** [appleboy/drone-ssh#146]
http://plugins.drone.io/appleboy/drone-ssh/
This still shoes me usage of `script` 

```
pipeline:
  ssh:
    image: appleboy/drone-ssh
    settings:
      host: foo.com
      username: root
      password: 1234
      port: 22
      script:
        - echo hello
        - echo world
```
as a result, when I updated to new format of `.drone.yml`, it was not running properly, so to speak, it hadn't ssh'ed into the host and was trying to run the commands on the agent itself.

is this compatible with 1.0+ or am I missing something?

In contrast, I can see updated format for slack plugin http://plugins.drone.io/drone-plugins/drone-slack/

**Comment by appleboy** [comment]
@arcolife new format as the following:

```yaml
- name: deploy
  image: appleboy/drone-ssh
  settings:
    host:
      - example.com
    user: deploy
    port: 22
    key:
      from_secret: ssh_key
    script:
      - cd cp && docker-compose pull api
      - docker-compose rm -sf api
      - docker-compose up -d
```

I will update the doc asap.
