### ISSUE TITLE
settings.envs does not work as expected

### ISSUE THREAD

**Issue by derekahn** [appleboy/drone-ssh#147]
> Example configuration for exporting custom secrets

☝️ I'm probably miss reading/understanding 🤷‍♂ 

## drone.yml
```yaml
    image: appleboy/drone-ssh
    settings:
      command_timeout: 2m
      envs:
        - git_url
      host: 10.10.10.1
      debug: true
      key:
        from_secret: ssh_key
      port: 22
      script:
        - export GIT_URL=$GIT_URL
        - env
      username: robo
```

<img width="948" alt="secret" src="https://user-images.githubusercontent.com/5381156/67249206-b507ea80-f41b-11e9-85b0-9d6c6eb751ae.png">

☝️ Isn't referencing these **secret**s  usually with `from_secret`?

## Result
```
======CMD======
1 | export GIT_URL=$GIT_URL
2 | env
3 | ======END======
4 | ======ENV======
5 |  
6 | ======END======
7 | out: GIT_URL=
```
