### ISSUE TITLE
ssh error on handshake

### ISSUE THREAD

**Issue by leonelfaugusto** [appleboy/drone-ssh#150]
Hello, 
After the last update on the docker outputs:
``2020/02/07 14:30:47 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain``

All work weel before the update.

My configuration:
```name: build dev
    image: appleboy/drone-ssh
    settings:
      host: MY_DOMAIN
      username: username
      key:
        from_secret: private_key
      script:
         - list with commands
    when:
      branch:
        - dev

**Comment by jled7** [comment]
Yes, i am having the same problem. Yesterday was working fine.

```
  ssh:
    image: appleboy/drone-ssh
    host: ip
    username: user
    password: pass
    port: 22
    script:
      - wine paint.exe
```

`[ssh:33] 2020/02/07 15:10:11 ssh: handshake failed: ssh: unable to authenticate, attempted methods [password none], no supported methods remain`

**Comment by leonelfaugusto** [comment]
For now, I'm using v1.5.5 that works fine.
Just replace ``appleboy/drone-ssh`` by  ``appleboy/drone-ssh:1.5.5`` on drone config file.

**Comment by ibantoo** [comment]
i got some error also
how to fix that ? i did like u said, but nothing

my .drone.yml 
```
kind: pipeline
name: trydrone

steps:
  - name: ssh
    image: appleboy/drone-ssh
    settings:
      host: myIP
      username: me
      password: 12345678
      port: 22
      script:
        - mkdir testdrone
```

when i use 

 key : `-----BEGIN OPENSSH PRIVATE KEY-----
     key here
-----END OPENSSH PRIVATE KEY-----`

my yml said bad synatx
