### ISSUE TITLE
Authentication failed after urfave/cli upgrade

### ISSUE THREAD

**Issue by milhouse1337** [appleboy/drone-ssh#151]
Hi Mr. Wu,

First just a quick word to say that this Docker image is very neat and useful, thank you for this! 😊

That said, since the upgrade of `urfave/cli` from `1.22.1` to `1.22.2` the autentication via public key is not working anymore.

> 2020/02/07 18:30:34 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

I think it has to do with the parameters, maybe they changed a bit. Here is my actual config:

```yaml
- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: host.example.com
    port: 22
    username: user
    key:
      from_secret: ...
    script:
      - ...
```

I temporarily fixed it with the last knowned working version (1.5.5) for now:
`image: appleboy/drone-ssh:1.5.5`

Thank you again!
