### ISSUE TITLE
Error: can't connect without a private SSH key or password

### ISSUE THREAD

**Issue by Hsueh-Jen** [appleboy/drone-ssh#153]
I use docker to run a CentOS container on localhost and I can use mac terminal and sftp software like Filezila to connect localhost:10022 successfully. And I want to use dorne-ssh to connect localhost but fail.

Here is my `.drone.yml` file

```yml
pipeline:

  ssh-deploy:
    image: appleboy/drone-ssh
    host: localhost
    password: 0000
    username: root
    port: 10022
    script:
      - echo hello
      - echo world
```

I use ` drone exec` to test, and it always response `Error: can't connect without a private SSH key or password`.  I want to use password, but I guess it didn't get the password.

I check the [DOCS.md](https://github.com/appleboy/drone-ssh/blob/master/DOCS.md) before.
and I place `host` in `settings`, and It says `Error: missing server host`.

So I don't really know what is the correct format. Could anyone help me? please.
