### ISSUE TITLE
How use multiline in script section

### ISSUE THREAD

**Issue by crojas** [appleboy/drone-ssh#163]
i want to do something like
```yaml
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      port: 22
      username:
        from_secret: ssh_username
      key:
        from_secret: ssh_key
      script:
        - docker rm -f ${DRONE_REPO_NAME}-${DRONE_BRANCH}
        - docker image rm user/${DRONE_REPO_NAME}:${DRONE_BRANCH}
        - docker run --rm -d \\
           --name ${DRONE_REPO_NAME}-${DRONE_BRANCH} \\
          --network development \\
          user/${DRONE_REPO_NAME}:${DRONE_BRANCH}
```
