### ISSUE TITLE
How to set environment variables?

### ISSUE THREAD

**Issue by softshipper** [appleboy/drone-ssh#164]
Hi all 

I have tried to set environment variables as follows:

```
  - name: Promote to STAGE
    image: appleboy/drone-ssh
    environment:
      GIT_REPO: ${DRONE_REPO}
      BUILD_NUMBER_REPO: ${DRONE_BUILD_NUMBER}
      SEMVER_REPO: ${DRONE_SEMVER_SHORT}
      ENV_REPO: stage
    settings:
      host: 111.111.111.111
      username: secret
      password: secret
      port: 22
      script:
        - echo $BUILD_NUMBER_REPO
        - drone build promote "$GIT_REPO" "$BUILD_NUMBER_REPO" "$ENV_REPO" --param=SEMVER_REPO="$SEMVER_REPO"
```
But it does not work. How to set it correctly?

Thanks
