### ISSUE TITLE
Secrets from Organization does not get taken

### ISSUE THREAD

**Issue by softshipper** [appleboy/drone-ssh#165]
Hi all 

I have created a secret per Organization as described on https://docs.drone.io/secret/organization/ that is used in the pipeline:
```
---
kind: pipeline
type: docker
name: Play with ssh

steps:
  - name: Promote to STAGE
    image: appleboy/drone-ssh
    settings:
      host: ci.example.io
      username: admin
      password:
        from_secret: ssh_password
      port: 22
      script:
        - echo "Welcome SSH"
        - ls -la

trigger:
  branch:
    - master
 ```
The secret does not get recognized from `Per Organization` but it recognizes when I put the secret in 
![Screenshot from 2020-10-07 15-39-24](https://user-images.githubusercontent.com/56756949/95338587-5f8a4f00-08b3-11eb-8a89-95df706c25ec.png)

Why it does not work the secret from `Per Organization`? 

Thanks
