### ISSUE TITLE
CMD empty and nothing gets executed

### ISSUE THREAD

**Issue by mschoettle** [appleboy/drone-ssh#166]
I am trying to use this plugin for the `promote` event as follows:

```yaml
steps:
- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: my.host.tld
    username:
      from_secret: ssh_user
    port: 1234
    key:
      from_secret: ssh_key
  script:
    - echo 'successfully connected to staging server'
    - ls -la
```

Unfortunately, the `CMD` section in the output is empty and nothing gets executed.
