### ISSUE TITLE
Secrets are not resolved

### ISSUE THREAD

**Issue by Frickeldave** [appleboy/drone-ssh#171]
Hi, 

i try to get a repo-secret from as described [here](https://github.com/appleboy/drone-ssh/blob/master/DOCS.md).
My .drone.yml file looks like this: 

```

kind: pipeline
type: docker
name: Jenkins management

steps:

######### TEMPLATES #########

- name: SSH template
  image: &imagessh appleboy/drone-ssh
  settings: &settingsssh
    host: TARGETHOST
    username: msghubadmin
    key:
      from_secret: msghubadmin-privatekey
    port: 22
    script: &scriptssh
      - export OIDC-CLIENT-SECRET-DEV=$${OIDC-CLIENT-SECRET-DEV}
      - echo "\"$OIDC_CLIENT_SECRET\" - \"$GITEA_API_USER_NAME\" - \"$GITEA_API_USER_PWD\""
      - echo "\"$${OIDC_CLIENT_SECRET}\" - \"$${GITEA_API_USER_NAME}\" - \"$${GITEA_API_USER_PWD}\""

  when:
    target:
    - template
.
.
.
######### Do the magic #########

- name: DEV-SSH Copy to container
  image: *imagessh
  settings:
    <<: *settingsssh
    host: my-dev-host.my.domain
    envs:
      - oidc-client-secret-dev
      - gitea-api-user-name-dev
      - gitea-api-user-pwd-dev
    script: *scriptssh
  when:
    target:
    - DEV

```
The complex template-anchor stuff works as expected. But when i run this example, the variables are not set. I tried the "export" command with $${var} as well as $var. Bot ends in the following output: 
```
======CMD======
export OIDC-CLIENT-SECRET-DEV=${OIDC-CLIENT-SECRET-DEV}
echo "\"$OIDC_CLIENT_SECRET\" - \"$GITEA_API_USER_NAME\" - \"$GITEA_API_USER_PWD\""
echo "\"${OIDC_CLIENT_SECRET}\" - \"${GITEA_API_USER_NAME}\" - \"${GITEA_API_USER_PWD}\""
======END======
err: bash: line 0: export: `OIDC-CLIENT-SECRET-DEV=CLIENT-SECRET-DEV': not a valid identifier
out: "" - "" - ""
out: "" - "" - ""
```
Please notice, that the "OIDC" is missing in the err output. I tired that all without the template anchor-stuff, with same result. 

Any idea, whats going wrong here?

I am using drone 1.9.2.

Regards

Dave

**Comment by Frickeldave** [comment]
Solved by myself, 2 minutes after writing this article. Thats working: 

```
- name: DEV-SSH Copy to container
  image: *imagessh
  environment:
    OIDC_CLIENT_SECRET:
      from_secret: oidc-client-secret-dev
    GITEA_API_USER_NAME:
      from_secret: gitea-api-user-name-dev
    GITEA_API_USER_PWD:
      from_secret: gitea-api-user-pwd-dev
  settings:
    <<: *settingsssh
    host: my-dev-host.my.domain
    envs:
      - OIDC_CLIENT_SECRET
      - GITEA_API_USER_NAME
      - GITEA_API_USER_PWD
    script: *scriptssh
  when:
    target:
    - DEV
```
