### ISSUE TITLE
using script_stop, there is a problem when using cat in script to output to a file.

### ISSUE THREAD

**Issue by heirychen** [appleboy/drone-ssh#175]
example file:

```
DRONE_SSH_PREV_COMMAND_EXIT_CODE=0 ; if [ 0 -ne 0 ]; then exit 0; fi;
version: '3.5'
DRONE_SSH_PREV_COMMAND_EXIT_CODE=0 ; if [ 0 -ne 0 ]; then exit 0; fi;
services:
DRONE_SSH_PREV_COMMAND_EXIT_CODE=0 ; if [ 0 -ne 0 ]; then exit 0; fi;
serve:
...
```

**Comment by heirychen** [comment]
my .drone.yml

```
kind: pipeline
type: docker
name: default

steps:
- name: deploy
  image: appleboy/drone-ssh
  pull: if-not-exists
  settings:
    host: 192.168.2.32
    username: root
    password:
      from_secret: ssh_password
    port: 22
    script_stop: true
    script:
    - mkdir -p /home/docker/test/${DRONE_REPO_NAMESPACE}-${DRONE_REPO_NAME}
    - cd /home/docker/test/${DRONE_REPO_NAMESPACE}-${DRONE_REPO_NAME}
    - |
      cat > ./docker-compose.yml << EOF
      version: '3.5'
      services:
        serve:
      EOF
    when:
      branch: [dev]
```
