### ISSUE TITLE
Executed script fails if a line contains a comma character (',')

### ISSUE THREAD

**Issue by smainz** [appleboy/drone-ssh#177]
When a script contains a comma char `,` the plugin intoduces a line break in the command, which leads to errors:
Example using docker:

```
docker run --rm   \
           -e PLUGIN_HOST="10.0.0.6"  \
           -e PLUGIN_USERNAME=data   \
           -e PLUGIN_PORT=2225   \
           -e PLUGIN_KEY="$PLUGIN_KEY"   \
           -e PLUGIN_DEBUG=true \
           -e PLUGIN_SCRIPT="echo a,b,c" \
           -v $(pwd):$(pwd)   \
           -w $(pwd)   \
           appleboy/drone-ssh
```

Output:
```
======CMD======
echo a
b
c
======END======
======ENV======

======END======
out: a
err: bash: line 2: b: command not found
err: bash: line 3: c: command not found
2022/03/03 11:35:39 Process exited with status 127
```

Here is a sample drone build file comparing simple commands with th applayboy/drone-ssh plugin:

```yaml
kind: pipeline
name: Build
type: docker

steps:
  - name: Test yaml local
    image: alpine/git
    commands:
      - "echo \"this, has, commas, and, is, in, double, quotes.\""
      - 'echo "this, has, commas, and, is, in, single, quotes."'
      - echo "This, has, commas, but, no, quotes"
      - echo "This,has,commas,without,spaces,and,no,quotes"
      - >
        echo "this, is, a, multiline,
        string, with, comma."
      - |
        echo "this, is, another, multiline, \
        string, with, comma."

  - name: Test yaml remote
    image: appleboy/drone-ssh
    settings:
      host: 10.0.0.6
      port: 2225
      username: data
      key:
        from_secret: SSH_KEY
      debug: true
      script:
        - "echo \"this, has, commas, and, is, in, double, quotes.\""
        - 'echo "this, has, commas, and, is, in, single, quotes."'
        - echo "This, has, commas, but, no, quotes"
        - echo "This,has,commas,without,spaces,and,no,quotes"
        - >
          echo "this, is, a, multiline,
          string, with, comma."
        - |
          echo "this, is, another, multiline, \
          string, with, comma."
```

Obviously the echo commands given to the alpine/git container and the appleboy/drone-ssh are the same, but the result while executing are completely different, as this plugin introduces line breaks instead of the commas:

console log of alpin/git:
```shell
latest: Pulling from alpine/git
Digest: sha256:d4740deff7f05d2d48771ff66d9d9c26dfb76f0db0aa833b1ea0ee346fa1e48f
Status: Image is up to date for alpine/git:latest
+ echo "this, has, commas, and, is, in, double, quotes."
this, has, commas, and, is, in, double, quotes.
+ echo "this, has, commas, and, is, in, single, quotes."
this, has, commas, and, is, in, single, quotes.
+ echo "This, has, commas, but, no, quotes"
This, has, commas, but, no, quotes
+ echo "This,has,commas,without,spaces,and,no,quotes"
This,has,commas,without,spaces,and,no,quotes
+ echo "this, is, a, multiline, string, with, comma."\n
this, is, a, multiline, string, with, comma.
+ echo "this, is, another, multiline, \\nstring, with, comma."\n
this, is, another, multiline, string, with, comma.
```

console log of appleboy/drone-ssh:
```shell
latest: Pulling from appleboy/drone-ssh
Digest: sha256:095ca4ceafcb751f1f22fe416057d3e2a6302f7b1f7011b17010973cb6bbdd9f
Status: Image is up to date for appleboy/drone-ssh:latest
======CMD======
echo "this
has
commas
and
is
in
double
quotes."
echo "this
has
commas
and
is
in
single
quotes."
echo "This
has
commas
but
no
quotes"
echo "This
has
commas
without
spaces
and
no
quotes"
echo "this
is
a
multiline
string
with
comma."
echo "this
is
another
multiline
\
string
with
comma."
======END======
======ENV======

======END======
out: this
out: has
out: commas
out: and
out: is
out: in
out: double
out: quotes.
out: this
out: has
out: commas
out: and
out: is
out: in
out: single
out: quotes.
out: This
out: has
out: commas
out: but
out: no
out: quotes
out: This
out: has
out: commas
out: without
out: spaces
out: and
out: no
out: quotes
out: this
out: is
out: a
out: multiline
out: string
out: with
out: comma.
out: this
out: is
out: another
out: multiline
out: string
out: with
out: comma.
==============================================
✅ Successfully executed commands to all host.
==============================================
```

I would have expected the output to be equal and in the form of the alpine/git image.
