### ISSUE TITLE
docker: command not found

### ISSUE THREAD

**Issue by wangpengzong** [appleboy/drone-ssh#180]
hello, I use in .drone.yml.
`uname -a`
 out: 
```
Linux DiskStation 4.4.59+ #23824 SMP PREEMPT Tue Feb 12 16:52:55 CST 2019 x86_64 GNU/Linux synology_apollolake_918+
```
This config:
```
kind: pipeline
type: docker
name: deployment

steps:
...
- name: deploy
  image: appleboy/drone-ssh
  pull: true
  settings:
    host: 191.168.0.22
    port: 22
    username: root
    password: 123456
    script: 
      - echo 从harbor拉取docker镜像
      - sudo docker pull mydomain.com:19080/library/k8s-netcore-demo:latest
      - sudo docker tag mydomain.com:19080/library/k8s-netcore-demo:latest wangpengzong/k8s-netcore-demo:latest
      - sudo docker run --name k8s-netcore-demo -p 29029:29029 wangpengzong/k8s-netcore-demo
      - echo docker容器启动成功
```
Output.
```
======CMD======
echo 从harbor拉取docker镜像
sudo docker pull mydomain.com:19080/library/k8s-netcore-demo:latest
sudo docker tag mydomain.com:19080/library/k8s-netcore-demo:latest wangpengzong/k8s-netcore-demo:latest
sudo docker run --name k8s-netcore-demo -p 29029:29029 wangpengzong/k8s-netcore-demo
echo docker容器启动成功
======END======
out: 从harbor拉取docker镜像
err: sudo: docker: command not found
err: sudo: docker: command not found
err: sudo: docker: command not found
out: docker容器启动成功
==============================================
✅ Successfully executed commands to all host.
==============================================
```
`ps aux | grep docker`
![image](https://user-images.githubusercontent.com/29770198/168839227-6dba02d6-c0b7-4251-bc37-60eeb46a9644.png)

how to deal with?
