### ISSUE TITLE
Cannot Use Secrets with Script for SSH Plugin

### ISSUE THREAD

**Issue by steve-gray** [appleboy/drone-ssh#19]
I've found that it's seemingly impossible to use secrets scoped to the SSH plugin with the script/commands section on 0.5 I'm guessing that the secrets are now only injected as parameters to the container, and not actually woven through the interpolated YAML (nor is there some means that I can seemingly find from the plugin side to trigger this interpolation into the script before submission to the remote). This means for example it's now impossible to pass some secret information as part of the commands to run on the SSH side.

Is there any means to get this going in 0.5 or is this a 'lost' feature as a consequence of the secrets architecture change?

-Steve

**Comment by appleboy** [comment]
@steve-gray update your drone to the latest version and try to add your secret via drone command line. You can use the secret on `secret` section.

```
drone secret add appleboy/drone-jenkins ABC 1234
```

in `.drone.yml`

```
  ssh:
    image: appleboy/drone-ssh
    pull: true
    host: www.che.ccu.edu.tw
    port: 22
    user: appleboy
    script:
      - ls -al
      - echo ${ABC}
    when:
      branch: master
      status: [ success ]
```

**Comment by Dineshs91** [comment]
@appleboy Is this still possible ? I am using `drone:0.8`. I want to add a custom secret so that I can use it in the script. 

```
dev-ssh:
    image: appleboy/drone-ssh
    username: ubuntu
    secrets:
      - source: DEV_HOST
        target: ssh_host
      - source: DEV_DEPLOY_KEY
        target: ssh_key
    script:
      - export tag=${DRONE_TAG}
      - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    when:
      event: tag
      branch: dev-*.*.*
```

The plugin expected secrets work just fine (ssh_host and ssh_key). But I also want to access the AWS_ACCESS_KEY_ID from the secret store. Is it possible ?
