### ISSUE TITLE
Environment variables correct usage

### ISSUE THREAD

**Issue by DennisGaida** [appleboy/drone-ssh#193]
I have found this issue: https://github.com/appleboy/drone-ssh/issues/135 and worked from there, I couldn't find this information in the DOCS: https://github.com/appleboy/drone-ssh/blob/master/DOCS.md

I'm trying to pass a variable to the  `script`. The current configuration works for me, I just don't know whether this is "best practice" or how to improve:

```yml
[...]
  image: appleboy/drone-ssh
  environment:
    FOO:
      from_secret:  FOO
  settings:
    [...]
    envs:
      - foo
    script:
      - echo "Starting script on '$(hostname)' in '$FOO'"
```
Instead of `environment` > `from_secret` I can also define the env var like so: `FOO: BAR`.

This seems kind of redundant using `environment` and `envs`, both defining "foo" or "FOO". Do I need both? I mean this currently works, it just looks weird in my eyes.

**Comment by CHunYenc** [comment]
Thanks @DennisGaida.

the code can work for me !

```
steps:
  - name: ssh
    image: appleboy/drone-ssh
    environment:
      PLUGIN_ENVS: SECRET_KEY, REDIS_HOST, REDIS_PORT
      SECRET_KEY:
        from_secret: SECRET_KEY
      REDIS_HOST:
        from_secret: REDIS_HOST
      REDIS_PORT:
        from_secret: REDIS_PORT
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port:
        from_secret: ssh_port
      command_timeout: 10m
      script:
        - echo SECRET_KEY = $${SECRET_KEY} > backend/.env
        - echo REDIS_HOST = $${REDIS_HOST} >> backend/.env
        - echo REDIS_PORT = $${REDIS_PORT} >> backend/.env
        - cat baclend/.env
```
