### ISSUE TITLE
all ssh executions fail eg "command not found"

### ISSUE THREAD

**Issue by Rainson12** [appleboy/drone-ssh#197]
```
  - name: update prod server to new build
    image: appleboy/drone-ssh
    environment:
      NEXUS_USERNAME:
        from_secret: nexus_username
      NEXUS_PASSWORD:
        from_secret: nexus_password
    settings:
      host: 192.168.72.179
      username:
        from_secret: ssh_username
      passphrase:
        from_secret: ssh_passphrase
      key:
        from_secret: ssh_key
      script:
        - echo "Replace dev container"
        - source envs.txt
```

the logs from drone:
```
1.6.3: Pulling from appleboy/drone-ssh
Digest: sha256:deffe56fdc80b90aa96c42c4d0525f040cb5a91319408745d436c0e8a2000c28
Status: Downloaded newer image for appleboy/drone-ssh:1.6.3
======CMD======
["echo \"Replace dev container\""
"source envs.txt"]
======END======
err: bash: [echo "Replace dev container": command not found
err: bash: line 1: source envs.txt: command not found
```

however when logging in manually to the server commands like `echo "Replace dev container"`  work completely fine
