### ISSUE TITLE
There are lots of empty error message!

### ISSUE THREAD

**Issue by wowuliao11** [appleboy/drone-ssh#199]
![image](https://user-images.githubusercontent.com/72588186/187656922-3f745490-1077-4bda-9fe4-58dba2cd8343.png)

But the last ,he tell me it's successful,and i really saw the output is right

![image](https://user-images.githubusercontent.com/72588186/187657286-a7f3a965-c537-4337-9c6d-68202ab75940.png)

This is my yml
```
steps:
  - name: ssh
    image: appleboy/drone-ssh
    settings:
      host:
        - *.*.*.* 
      key:
        from_secret: rsa_key
      username: root
      command_timeout: 2m
      script:
        - echo "Hello ssh plugin"
        - cd /home/danny/backup/mongodb_bak
        - ls
```

please!😭
