### ISSUE TITLE
sending notification about build result

### ISSUE THREAD

**Issue by Datawords-HK** [appleboy/drone-ssh#202]
I want to receive notification about build result (success or failed).

It seems the build result is not brought to the notification step.

![image](https://user-images.githubusercontent.com/110004165/198463772-240352e1-ab1f-4d89-866f-e79bec9874f0.png)

![image](https://user-images.githubusercontent.com/110004165/198463841-ba546a15-f718-412c-8310-f88fd868216d.png)

![telegram](https://user-images.githubusercontent.com/110004165/198466059-3bbf6422-b74f-40b0-aed4-09ae0ef9cf86.jpg)

Below is the `.drone.yaml`:
```
kind: pipeline
type: docker
name: deploy-to-staging

trigger:
  branch:
    - develop

clone:
  disable: true

steps:
  - name: deploy-to-staging
    image: appleboy/drone-ssh:1.6.3
    failure: ignore
    settings:
      host:
        from_secret: STG-Server
      username:
        from_secret: STG-Server-UserName
      password:
        from_secret: STG-Server-Password
      script:
        - cd /home/graff/frontend
        - git pull origin develop
  - name: send telegram notification
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: TELEGRAM-TOKEN
      to:
        from_secret: TELEGRAM-CHANNEL-ID
  - name: send email notification
    image: drillster/drone-email
    settings:
      host:
        from_secret: SMTP-HOST
      username:
        from_secret: SMTP-USERNAME
      password:
        from_secret: SMTP-PASSWORD
      from:
        from_secret: SMTP-USERNAME

---

kind: pipeline
type: docker
name: deploy-to-production

trigger:
  branch:
    - production

clone:
  disable: true

steps:
  - name: deploy-to-staging
    image: appleboy/drone-ssh:1.6.3
    failure: ignore
    settings:
      host:
        from_secret: PROD-Server
      username:
        from_secret: PROD-Server-UserName
      password:
        from_secret: PROD-Server-Password
      script:
        - cd /home/graffprod/frontend
        - git pull origin production
  - name: send telegram notification
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: TELEGRAM-TOKEN
      to:
        from_secret: TELEGRAM-CHANNEL-ID
  - name: send email notification
    image: drillster/drone-email
    settings:
      host:
        from_secret: SMTP-HOST
      username:
        from_secret: SMTP-USERNAME
      password:
        from_secret: SMTP-PASSWORD
      from:
        from_secret: SMTP-USERNAME
```

Thanks.
