### ISSUE TITLE
ssh: handshake failed: ssh: unable to authenticate

### ISSUE THREAD

**Issue by bbaulenas** [appleboy/drone-ssh#203]
Hi! I'm having an issue using key from secret, I have read all the posts from the issues but none of them works.

Error
```
latest: Pulling from appleboy/drone-ssh
Digest: sha256:49d38c9c2990d0234d73afd07c409410ac2f24ef69014bcbbf52019411bd9683
Status: Image is up to date for appleboy/drone-ssh:latest
======CMD======
ls
======END======
2022/10/28 10:48:27 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

.drone.yml
```
kind: pipeline
name: default

steps:
- name: ssh
  image: appleboy/drone-ssh
  settings:
    host:
      - xxxx.com
    username: root
    key:
      from_secret: ssh_key
    port: 22
    command_timeout: 2m
    script:
      - ls

trigger:
  branch:
  - master
```

The value of ssh_key secret is the rsa string, is this ok?

Thank you!

**Comment by bbaulenas** [comment]
I'm sorry. I misstyped the key. 

It works perfectly. Sorry.

Thank you!

**Comment by devcxl** [comment]
I added it using the command line tool ：

drone secret add --repository repo/demo --name SSH_KEY --data @/home/root/.ssh/id_ed25519

This is my  `.drone.yml`  config：
```yaml
kind: pipeline
type: docker
name: deploy

trigger:
    event:
        - promote
    target:
        - staging

steps:
    - name: deploy
      image: appleboy/drone-ssh
      settings:
          host:
              - myhost
          username:
              from_secret : SSH_USERNAME
          key:
              from_secret: SSH_KEY
          port: 22
          command_timeout: 2m
          script:
              - echo "Hello World" > test.txt
```

But it doesn't work properly：

ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
