### ISSUE TITLE
Since 1.6.5, I have the following error : "manifest for appleboy/drone-ssh:1.6.5-linux-amd64 not found: manifest unknown: manifest unknown"

### ISSUE THREAD

**Issue by GeoDaz** [appleboy/drone-ssh#205]
My Pipeline : 
```yml
name: Test deployment
on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  node_dependencies:
    name: yarn build them deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: "Node modules installation"
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: yarn install
      - run: yarn encore production

      - name: "Remove remote front build"
        uses: appleboy/ssh-action@master
        with:
          host: ...
          port: ...
          username: ...
          key: ...
          passphrase: ...
          script: rm -r ...

      - name: "Send front build to remote"
        uses: appleboy/scp-action@master
        with:
          source: "./public/build"
          host: ...
          port: ...
          username: ...
          key: ...
          passphrase: ...
          target: ...
          
      - name: "Run deploy : git pull, composer install and update bdd"
        uses: appleboy/ssh-action@master
        with:
          host: ...
          port: ...
          username: ...
          key: ...
          passphrase: $...
          script: cd ... && ....sh

```
