### ISSUE TITLE
the image latest can't execute script correctly

### ISSUE THREAD

**Issue by theonlyu** [appleboy/drone-ssh#214]
the update latest can't execute script correctly.

before normal
![admin](https://user-images.githubusercontent.com/75383020/209496121-37f4a216-f40a-4b8b-bad0-2ea843da13bb.png)

now
![admin2](https://user-images.githubusercontent.com/75383020/209496133-98d69840-2ebd-45b6-91a7-5284010064a1.png)

if want to normal, just need change image old version in .drone.yml.

example:
 image: appleboy/drone-ssh:1.6.4

**Comment by sanguohot** [comment]
I just found the same error. I think it is because of the cli/v2.

**Comment by buddy-yao** [comment]
I encountered the same problem

**Comment by itmisx** [comment]
I encountered the same problem

**Comment by CHunYenc** [comment]
Version (```appleboy/drone-ssh:1.6.4```) has a lot of empty message

I used ```appleboy/drone-ssh:1.6.5-linux-amd64``` is ok.

```yml
# .drone.yml
kind: pipeline
type: docker
name: default

....

steps:
- name: deploy
  image: appleboy/drone-ssh:1.6.5-linux-amd64
  settings:
    host:
      from_secret: ssh_host
    port:
      from_secret: ssh_port
    username:
      from_secret: ssh_username
    password:
      from_secret: ssh_password
    command_timeout: 10m
    script:
      - sudo su
      - mkdir application
      - echo "Deleted application folder."
```

result:
```shell
# output
root@vm:/home/system# drone exec --secret-file .secrets --include deploy
2022/12/26 16:52:34 proto: duplicate proto type registered: PluginSpec
2022/12/26 16:52:34 proto: duplicate proto type registered: PluginPrivilege
No stage specified, assuming 'default'
[deploy:1] ======CMD======
[deploy:2] sudo su
[deploy:3] mkdir application
[deploy:4] echo "Deleted application folder."
[deploy:5] ======END======
[deploy:6] out: Deleted application folder.
[deploy:7] ==============================================
[deploy:8] ✅ Successfully executed commands to all host.
[deploy:9] ==============================================
```

#ssh's machine
```shell
drone@vm:~$ ls
application
```
