### ISSUE TITLE
 Unable to execute docker command

### ISSUE THREAD

**Issue by tomekbielaszewski** [appleboy/drone-ssh#221]
This issue was originally reported in [here](https://github.com/appleboy/ssh-action/issues/210). At the bottom I will provide an example of reproduced issue using CLI

When I use the ssh Github Action I'm unable to execute some commands. I get results like these executables did not exist on my server.

I have the action set up like that: 

```
uses: appleboy/ssh-action@v0.1.7
with:
  host: ${{ secrets.IP }}
  username: ${{ secrets.USERNAME }}
  password: ${{ secrets.PASSWORD }}
  script: |
    which docker
    docker --version
```

When I execute this command on my server by ssh'ing manually from my home laptop and using exactly the same user - I will get the following result:

```
~$ which docker
/usr/local/bin/docker
~$ docker --version
Docker version 20.10.3, build 55f0773
```

but when I execute exactly the same commands, from Github Action above, I get:

```
======CMD======
which docker
docker --version

======END======
2023/01/08 20:49:04 Process exited with status 127
err: sh: line 1: docker: command not found
```

This can be reproduced with the `drone-ssh` tool which is a direct dependency for the `appleboy/ssh-action`:

`./drone-ssh -H my_server_ip -u my_user -P my_password -s "docker --version"`
results with:
```
======CMD======
docker --version
======END======
err: sh: docker: command not found
2023/01/08 22:19:22 Process exited with status 127
```

What can be the cause of missing executables/commands when ssh'ing with this tool? This does not happen when using standard `ssh`

**Comment by tomekbielaszewski** [comment]
I had this issue when interacting with Synology NAS through non-interactive ssh. It appears that I have `docker` in `/usr/local/bin/`. This directory is not in PATH when executing commands remotely through ssh like so:
`ssh username@server_ip "docker --version"`
but when logging I'm into the server through ssh this directory is loaded into PATH.

My solution for the issue above was to specify full path to docker executable as follows:
```
uses: appleboy/ssh-action@v0.1.7
with:
  host: ${{ secrets.IP }}
  username: ${{ secrets.USERNAME }}
  password: ${{ secrets.PASSWORD }}
  script: |
    /usr/local/bin/docker --version
```
