### ISSUE TITLE
SSH port gets included twice in SSH command

### ISSUE THREAD

**Issue by saintaardvark** [appleboy/drone-ssh#35]
Hi there -- we're seeing a bug when using the SSH plugin for drone.  Despite changing the format of .drone.yml a few times, we're consistently seeing this when it runs:

```
[info] Pulling image plugins/drone-ssh:latest
Drone SSH Plugin built from 673599f
$ ssh dronedeploy@dogfood.example.com:22 -p 22
error: <class 'socket.error'>, [Errno 13] Permission denied: file: /usr/lib/python2.7/socket.py line: 228
error: <class 'socket.error'>, [Errno 13] Permission denied: file: /usr/lib/python2.7/socket.py line: 228
Process exited with status 2
[info] build failed (exit code 1)
```

Note the doubled port in the SSH command -- both ":22" and "-p 22".

The SSH stanza in our .drone.yml file looks like this:

```yaml
deploy: 
 ssh:
    host: dogfood.example.com
    user: dronedeploy
    commands:
      - /path/to/script.sh
```

However, we've also tried explicitly specifying the port:

```yaml
deploy: 
 ssh:
    host: dogfood.example.com
    user: dronedeploy
    port: 22
    commands:
      - /path/to/script.sh
```
and we see the same output.

The problem *appears* to be that the port is added explicitly to the address at https://github.com/appleboy/drone-ssh/blob/master/plugin.go#L70-L74:

```go
	for i, host := range p.Config.Host {
		addr := net.JoinHostPort(
			host,
			strconv.Itoa(p.Config.Port),
		)
```

This ends up being a duplicate of https://github.com/appleboy/drone-ssh/blob/master/plugin.go#L111, where the config struct is used to run ssh.Dial:

```go
		client, err := ssh.Dial("tcp", addr, config)
```

Since the port is included in the Config struct at https://github.com/appleboy/drone-ssh/blob/master/plugin.go#L32, I'm assuming that's where the duplicate port argument is coming from.
