### ISSUE TITLE
can't connect without a private SSH key or password

### ISSUE THREAD

**Issue by webpolis** [appleboy/drone-ssh#49]
Hi

This is my current configuration in my CI instance:

```
appleboy/drone-ssh                       latest              df47ad550951        2 days ago          11.7 MB
drone/drone                              0.5                 bad42d215125        6 days ago          26.6 MB
```

and my _.drone.yml_'s ssh section looks like

```
  ssh:
    image: appleboy/drone-ssh
    when:
      branch: [staging, production]
    host: ${DRONE_BRANCH}.xxxxx.com
    port: 9999
    user: root
    keyPath: /root/${DRONE_BRANCH}.key
```
I have that _/root/..._ path attached to the drone image via the _volume_ setting in my docker-compose.yml, and the different environments .key files are available, but Drone still fails to proceed with the build:

```
Error: can't connect without a private SSH key or password
```

Can anyone tell me what I'm doing wrong?

Thanks in advance
