### ISSUE TITLE
Deploy steps continue even if command returns error

### ISSUE THREAD

**Issue by mattbucci** [appleboy/drone-ssh#66]
Is there any way to abort execution on error? for instance right now In my deployment code I run gulp through your ssh plugin, if gulp returns a compile error I want to abort, but currently that does not happen.

I am going to wrap all my build steps in a bash script with stricter error handling, but I wanted to check if there was another way first. 

Here's what my .drone.yml currently looks like

```
deploy:
  ssh:
    host: gwizlv-prd01
    user: crun
    port: 22
    commands:
      - setenv build `date +%s`
      - setenv appdir "/mnt/shared/sites/people"
      - mkdir $appdir/releases/$build/
      - cd $appdir/releases/$build/
      - git clone <git repo> ./
      - composer install --no-interaction
      - cp .env.production .env
      - phpunit
      - rm -rf storage
      - ln -s $appdir/storage storage
      - php artisan clear-compiled
      - php artisan optimize
      - npm install
      - gulp
      - php artisan migrate --no-interaction --force
      - find ./ -type d -exec chmod 775 {} +
      - find ./ -type f -exec chmod 664 {} +
      - cd $appdir
      - ln -n -f -s $appdir/releases/$build $appdir/release
      - ln -n -f -s $appdir/releases/$build $appdir/last_release
    when:
      branch: master
```

**Comment by appleboy** [comment]
@mattbucci I will add new flag to ignore command error and set default behavior is abort execution on any error. Thnaks for your reminder.

**Comment by appleboy** [comment]
maybe duplicated of #75

**Comment by appleboy** [comment]
@mattbucci Can you help me to try the latest image? Give me feedback if success or fail.

**Comment by mattbucci** [comment]
@appleboy unsure if I need to run something manually to update but basic commands failing aren't working in my deploy Maybe exit 1 will?

```
$ sudo docker pull plugins/drone-ssh:latest
latest: Pulling from docker.io/plugins/drone-ssh
4aa0bf7eb856: Already exists
30a800db6329: Already exists
f13767770ce7: Already exists
e883002bb836: Already exists
Digest: sha256:c0e268a585f420ac986668004537fe81fdb07728ab8a8dc964f40e1082cde5c8
Status: Image is up to date for docker.io/plugins/drone-ssh:latest
```

This does not exit
```
[info] Pulling image plugins/drone-ssh:latest
Drone SSH Plugin built from 673599f
$ ssh crun@gwizlv-qa01:22 -p 22
mkdir: cannot create directory ‘/mnt/shared/sites/people/releases/177/’: File exists
fatal: destination path '.' already exists and is not an empty directory.
---- more commands keep executing below
```

**Comment by appleboy** [comment]
@mattbucci Wrong name. The correct name is `appleboy/drone-ssh`.

**Comment by mattbucci** [comment]
Thanks! I see that in your readme now that the other plugin is unmaintained. I will try again and post and update here.

**Comment by appleboy** [comment]
@mattbucci Looking forward your feedback.

**Comment by mattbucci** [comment]
@appleboy Still seems to be occuring on 0.5

It actually returned that everything passed as well. I would have expected execution to stop here:
err: mkdir: cannot create directory ‘/mnt/shared/sites/people/releases/11/’: File exists

![screen shot 2017-05-11 at 12 35 10 pm](https://cloud.githubusercontent.com/assets/3284147/25968433/51ccec6c-3646-11e7-947d-05cf5c727d2d.jpg)

**Comment by appleboy** [comment]
@mattbucci I added test example https://github.com/appleboy/drone-ssh/blob/master/plugin_test.go#L195-L209 and got exit code 1

![screen shot 2017-05-12 at 4 53 10 pm](https://cloud.githubusercontent.com/assets/21979/25990779/8cdd6802-3733-11e7-8f9d-e8d6285fa952.png)

**Comment by mattbucci** [comment]
@appleboy if you look at mine you'll see it also returns that it was an err, it just still continues. I'm not sure what to tell you

**Comment by mattbucci** [comment]
here's my config, hopefully that helps

```
 ssh:
    image: appleboy/drone-ssh
    host: gwizlv-prd01
    user: crun
    key: ${SSH_KEY}
    port: 22
    command_timeout: 600
    script:
      - setenv build ${DRONE_BUILD_NUMBER}
      - setenv appdir "/mnt/shared/sites/people"
      - mkdir $appdir/releases/$build/
      - if ( `readlink "$appdir/release" | xargs basename` == ${DRONE_BUILD_NUMBER}) echo "Build Already Deployed, cannot redeploy without causing downtime"
      - if ( `readlink "$appdir/release" | xargs basename` == ${DRONE_BUILD_NUMBER}) exit 1
      - cd $appdir/releases/$build/
      - git clone -b ${DRONE_COMMIT_BRANCH} --single-branch git@gitlab.gene.com:${DRONE_REPO}.git ./
      - git reset --hard ${DRONE_COMMIT_REF}
      - composer install --no-interaction
      - cp .env.production .env
      - vendor/bin/phpunit
      - rm -rf storage
      - ln -s $appdir/storage storage
      - php artisan clear-compiled
      - php artisan optimize --force
      - php artisan route:cache
      - npm install
      - gulp
      - if ( `readlink "$appdir/release" | xargs basename` >= ${DRONE_BUILD_NUMBER} ) echo "ABORTED - BUILD RACE CONDITION MET"
      - if ( `readlink "$appdir/release" | xargs basename` >= ${DRONE_BUILD_NUMBER}) exit 1
      - echo "Build is New - Proceeding to update the live app"
      - # if QA, dump latest PRD database into QA
      - php artisan migrate --no-interaction --force
      - find ./ -type d -exec chmod 775 {} +
      - find ./ -type f -exec chmod 664 {} +
      - cd $appdir
      - ln -n -f -s $appdir/releases/$build $appdir/release
      - ln -n -f -s $appdir/releases/$build $appdir/last_release
    when:
      branch: prod
```
