### ISSUE TITLE
secrets in drone 0.6

### ISSUE THREAD

**Issue by ecwyne** [appleboy/drone-ssh#73]
I'm trying to use secrets with `drone-ssh` and my 0.6 install

I've tried both
```yaml
pipeline:
  deploy:
    image: appleboy/drone-ssh
    username: root
    secrets: [deploy_host, deploy_password]
    script: ...
```
and
```yaml
pipeline
  deploy:
    image: appleboy/drone-ssh
    username: root
    secrets: [drone-ssh_host, drone-ssh_password]
    script: ...
```

Either way I get the following error:
`Error: can't connect without a private SSH key or password`

Does the new secrets syntax work with `drone-ssh`?
http://docs.drone.io/manage-secrets/

**Comment by ecwyne** [comment]
I got some help on gitter. 
It looks like there are two possible options

```yaml
secrets: [ssh_username, ssh_password]
```
or
```yaml
secrets: 
  - username: [arbitrary_secret_name]
  - password: [another_arbitrary_name]
```
