### ISSUE TITLE
Build status failure when command returns exit code != 0

### ISSUE THREAD

**Issue by asosso** [appleboy/drone-ssh#75]
How can I stop the build when command returns non-exit 0 status code?

At the end of `appleboy/drone-ssh` pipeline, I always see "Successfully executed commands to all host." and the build continue. 

### .drone.yml using appleboy/drone-ssh

```
  deploy-dev:
    image: appleboy/drone-ssh
    host:
     - 192.168.1.2
    username: root
    port: 22
    script:
      - exit 1
```

**Output**

```
2017/05/07 13:47:32 192.168.1.2: commands:  exit 1
2017/05/07 13:47:34 192.168.1.2: outputs: 
2017/05/07 13:47:34 Successfully executed commands to all host.
```

The build continue...

### .drone.yml using plugin/ssh

```
  deploy-dev:
    image: plugins/ssh
    host:
     - 192.168.1.2
    username: root
    port: 22
    script:
      - exit 1
```

**Output**

```
ssh root@192.168.1.2:22 -p 22
Process exited with status 1
```

The build fail!

**Comment by appleboy** [comment]
@asosso I will take it.

**Comment by appleboy** [comment]
@asosso Please try the latest docker image.

**Comment by asosso** [comment]
Thank you, it works!

### .drone.yml

```
  deploy-dev:
    image: appleboy/drone-ssh
    host:
     - 192.168.1.2
    username: root
    port: 22
    script:
      - exit 1
      - exit 2
      - exit 0
```

### Output

```
2017/05/09 08:25:25 192.168.1.2: commands:  exit 1
exit 2
exit 0
2017/05/09 08:25:28 192.168.1.2: outputs: 
2017/05/09 08:25:28 drone-ssh error:  Process exited with status 1
Process exited with status 1
```
