### ISSUE TITLE
plugin doesn't read in secrets for drone:0.6/0.7?

### ISSUE THREAD

**Issue by PeterCat12** [appleboy/drone-ssh#87]
I believe this is due to the way secrets are done in drone/0.6 (and subsequently 7), however, I have only tested in drone/0.7

relevant part of my `drone.yml`:

```
ssh-deploy:
    image: appleboy/drone-ssh
    port: 22
    pull: true
    command_timeout: 180
    secrets: [ host, user, key ]
```

With this configuration I get the following error:
```
Error: can't connect without a private SSH key or password
```

I've tried my old drone configuration that worked in 0.5 and still could not connect to my instance. Anyone else experiencing this? If not then I'll chalk it up to setting my secrets incorrectly (though I am fairly certain they are set correctly)...
