### ISSUE TITLE
pass drone environment variables

### ISSUE THREAD

**Issue by matteosuppo** [appleboy/drone-ssh#89]
```
  deploy:
    image: appleboy/drone-ssh
    host: salt.arduino.cc
    user: admin
    port: 22
    secrets: [ssh_key]
    script:
      - \[ "$DRONE_DEPLOY_TO" = "dev" \] && target=api-dev
      - \[ "$DRONE_DEPLOY_TO" = "prod" \] && target=api-prod
      - echo $target
      - printenv
      - sudo salt -G node_type:$target state.highstate
    when:
      event: deployment
```

Basically I would like to use the drone-defined environment variables on the remote server. Is there a way to do it?
